version: "3"
services:
  mongodb:
    image: 'mongo'
    ports: 
      - "27018:27017"
    volumes:
      - /data:/data/db
  backend:
    build: ./
    ports: 
      - "3012:3012"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb  
    command: "npm run start:legacy"